[build]
  HUGO_VERSION = "0.89.4"
  GO_VERSION = "1.17.3"
  HUGO_ENABLEGITINFO = "true"
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  HUGO_VERSION = "0.89.4"
  GO_VERSION = "1.17.3"
  HUGO_ENV = "deploy-preview"
  HUGO_ENABLEGITINFO = "true"
  command = "npm run build-preview"
